'use client';
// AUTO-GENERATED by w-research-kb.py — no-scroll KB index
// SurfaceTabs
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { BookOpen, ClipboardCheck, KeyRound, Sparkles } from 'lucide-react';
import { useTheme } from '@/context/ThemeContext';
import { ZetaNavbar } from '@/components/ui/ZetaNavbar';
import { KB_CHAPTERS } from '@/data/kb-chapters';
import { KB_MODULES, KB_CAPABILITIES } from '@/data/kb-index';

type Tab = 'chapters' | 'modules' | 'capabilities';

const TABS: { id: Tab; label: string; Icon: typeof BookOpen }[] = [
  { id: 'chapters', label: 'Chapters', Icon: BookOpen },
  { id: 'modules', label: 'Modules', Icon: ClipboardCheck },
  { id: 'capabilities', label: 'Capabilities', Icon: KeyRound },
];

export default function KBIndexSurface() {
  const { theme } = useTheme();
  const [tab, setTab] = useState<Tab>('chapters');

  const isDark = theme === 'dark';
  const bg = isDark ? 'bg-[#0A0A0F]' : 'bg-[#FAF9F3]';
  const cardBg = isDark ? 'bg-white/[0.03]' : 'bg-white';
  const border = isDark ? 'border-white/10' : 'border-black/10';
  const text = isDark ? 'text-white' : 'text-black';
  const muted = isDark ? 'text-white/60' : 'text-black/60';
  const activeTab = isDark ? 'bg-white/10 text-white' : 'bg-black/10 text-black';
  const idleTab = isDark ? 'text-white/60 hover:text-white' : 'text-black/60 hover:text-black';

  const content = useMemo(() => {
    if (tab === 'chapters') {
      return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 overflow-y-auto pr-2 h-full">
          {KB_CHAPTERS.map((c) => (
            <Link
              key={c.slug}
              href={`/kb/${c.slug}/`}
              className={`block rounded-2xl border ${border} ${cardBg} p-4 hover:border-[#E9ED4C] transition-colors`}
            >
              <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>{c.eyebrow} · Chapter {c.num}</div>
              <div className={`text-base font-medium mt-1 ${text}`}>{c.title}</div>
              <div className={`text-xs mt-2 ${muted} line-clamp-2`}>{c.body[0]}</div>
            </Link>
          ))}
        </div>
      );
    }
    if (tab === 'modules') {
      return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 overflow-y-auto pr-2 h-full">
          {KB_MODULES.map((m) => (
            <Link
              key={m.slug}
              href={`/kb/${m.slug}/`}
              className={`block rounded-2xl border ${border} ${cardBg} p-4 hover:border-[#E9ED4C] transition-colors`}
            >
              <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>{m.id} · {m.type.replace(/_/g, ' ')}</div>
              <div className={`text-base font-medium mt-1 ${text}`}>{m.name}</div>
              <div className={`text-xs mt-2 ${muted}`}>{m.oneLiner}</div>
            </Link>
          ))}
        </div>
      );
    }
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 overflow-y-auto pr-2 h-full">
        {KB_CAPABILITIES.map((cap) => (
          <div
            key={cap.slug}
            className={`rounded-2xl border ${border} ${cardBg} p-4`}
          >
            <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>{cap.code}</div>
            <div className={`text-base font-medium mt-1 ${text}`}>{cap.name}</div>
            <div className={`text-xs mt-2 ${muted}`}>{cap.oneLiner}</div>
          </div>
        ))}
      </div>
    );
  }, [tab, border, cardBg, muted, text]);

  return (
    <div className={`h-screen flex flex-col overflow-hidden ${bg} ${text}`}>
      <ZetaNavbar />
      <header className={`px-6 md:px-10 py-5 border-b ${border} flex items-center justify-between`}>
        <div>
          <div className={`text-[11px] uppercase tracking-[0.18em] ${muted}`}>Knowledge base</div>
          <h1 className="text-2xl md:text-3xl font-semibold mt-1">Chapters, modules, capabilities — one index.</h1>
        </div>
        <Link
          href="/ledger/"
          className={`hidden md:flex items-center gap-2 text-xs uppercase tracking-[0.14em] ${muted} hover:${text}`}
        >
          <Sparkles className="w-3.5 h-3.5" />
          Open the public ledger
        </Link>
      </header>
      <div className={`px-6 md:px-10 py-3 border-b ${border} flex gap-2`}>
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs uppercase tracking-[0.14em] transition-colors ${tab === t.id ? activeTab : idleTab}`}
          >
            <t.Icon className="w-3.5 h-3.5" />
            {t.label}
          </button>
        ))}
      </div>
      <main className="flex-1 min-h-0 px-6 md:px-10 py-4">{content}</main>
    </div>
  );
}
