'use client';
// AUTO-GENERATED by w-research-kb.py — no-scroll KB module drill-down
// SurfaceTabs
import Link from 'next/link';
import { useMemo } from 'react';
import { ArrowLeft, Sparkles } from 'lucide-react';
import { useTheme } from '@/context/ThemeContext';
import { ZetaNavbar } from '@/components/ui/ZetaNavbar';
import { getModule, KB_MODULES } from '@/data/kb-index';
import { getChapter, KB_CHAPTERS } from '@/data/kb-chapters';

export default function KBModuleDetail({ slug }: { slug: string }) {
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const bg = isDark ? 'bg-[#0A0A0F]' : 'bg-[#FAF9F3]';
  const cardBg = isDark ? 'bg-white/[0.03]' : 'bg-white';
  const border = isDark ? 'border-white/10' : 'border-black/10';
  const text = isDark ? 'text-white' : 'text-black';
  const muted = isDark ? 'text-white/60' : 'text-black/60';

  const { module, chapter } = useMemo(() => {
    const mod = getModule(slug);
    if (mod) return { module: mod, chapter: getChapter(mod.chapterSlug) };
    const ch = getChapter(slug);
    return { module: undefined, chapter: ch };
  }, [slug]);

  if (!module && !chapter) {
    return (
      <div className={`h-screen flex flex-col overflow-hidden ${bg} ${text}`}>
        <ZetaNavbar />
        <main className="flex-1 min-h-0 px-6 md:px-10 py-6 flex flex-col items-center justify-center">
          <div className={`text-sm ${muted}`}>Not found in the knowledge base.</div>
          <Link href="/kb/" className={`mt-3 text-xs uppercase tracking-[0.14em] ${text} border border-current px-3 py-1 rounded-full`}>
            <ArrowLeft className="inline w-3.5 h-3.5 mr-1" /> Back to the KB
          </Link>
        </main>
      </div>
    );
  }

  if (module) {
    return (
      <div className={`h-screen flex flex-col overflow-hidden ${bg} ${text}`}>
        <ZetaNavbar />
        <header className={`px-6 md:px-10 py-5 border-b ${border}`}>
          <Link href="/kb/" className={`text-[11px] uppercase tracking-[0.14em] ${muted} inline-flex items-center gap-1`}>
            <ArrowLeft className="w-3.5 h-3.5" /> Back to the KB
          </Link>
          <div className={`text-[11px] uppercase tracking-[0.18em] ${muted} mt-3`}>{module.id} · {module.type.replace(/_/g, ' ')}</div>
          <h1 className="text-2xl md:text-3xl font-semibold mt-1">{module.name}</h1>
          <p className={`text-sm mt-2 ${muted}`}>{module.oneLiner}</p>
        </header>
        <main className={`flex-1 min-h-0 px-6 md:px-10 py-5 grid grid-cols-1 md:grid-cols-[1fr_320px] gap-4`}>
          {chapter ? (
            <section className={`rounded-2xl border ${border} ${cardBg} p-5 min-h-0 overflow-y-auto`}>
              <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>Anchored to chapter {chapter.num}</div>
              <h2 className={`text-lg font-medium mt-1 ${text}`}>{chapter.title}</h2>
              <div className={`mt-3 space-y-2 text-sm leading-relaxed ${muted}`}>
                {chapter.body.map((p, i) => <p key={i}>{p}</p>)}
              </div>
            </section>
          ) : (
            <section className={`rounded-2xl border ${border} ${cardBg} p-5 ${muted} text-sm`}>
              This module is not yet anchored to a chapter.
            </section>
          )}
          <aside className={`rounded-2xl border ${border} ${cardBg} p-5 flex flex-col gap-3 min-h-0`}>
            <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>Next step</div>
            <p className={`text-sm ${text}`}>See the module in action inside the public ledger.</p>
            <Link
              href="/ledger/"
              className={`inline-flex items-center gap-2 text-xs uppercase tracking-[0.14em] ${text} border border-current px-3 py-1.5 rounded-full self-start`}
            >
              <Sparkles className="w-3.5 h-3.5" /> Open the ledger
            </Link>
          </aside>
        </main>
      </div>
    );
  }

  // chapter view
  return (
    <div className={`h-screen flex flex-col overflow-hidden ${bg} ${text}`}>
      <ZetaNavbar />
      <header className={`px-6 md:px-10 py-5 border-b ${border}`}>
        <Link href="/kb/" className={`text-[11px] uppercase tracking-[0.14em] ${muted} inline-flex items-center gap-1`}>
          <ArrowLeft className="w-3.5 h-3.5" /> Back to the KB
        </Link>
        <div className={`text-[11px] uppercase tracking-[0.18em] ${muted} mt-3`}>{chapter!.eyebrow} · Chapter {chapter!.num}</div>
        <h1 className="text-2xl md:text-3xl font-semibold mt-1">{chapter!.title}</h1>
      </header>
      <main className={`flex-1 min-h-0 px-6 md:px-10 py-5 grid grid-cols-1 md:grid-cols-[1fr_320px] gap-4`}>
        <section className={`rounded-2xl border ${border} ${cardBg} p-5 min-h-0 overflow-y-auto space-y-3 text-sm leading-relaxed ${muted}`}>
          {chapter!.body.map((p, i) => <p key={i} className={text}>{p}</p>)}
        </section>
        <aside className={`rounded-2xl border ${border} ${cardBg} p-5 flex flex-col gap-3 min-h-0 overflow-y-auto`}>
          <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>Related modules</div>
          {KB_CHAPTERS.filter((c) => c.slug === chapter!.slug).length > 0 && (
            <div className="flex flex-col gap-2">
              {/* modules that link to this chapter */}
              {KB_MODULES
                .filter((m) => m.chapterSlug === chapter!.slug)
                .map((m) => (
                  <Link
                    key={m.slug}
                    href={`/kb/${m.slug}/`}
                    className={`block rounded-xl border ${border} p-3 hover:border-[#E9ED4C] transition-colors`}
                  >
                    <div className={`text-[11px] uppercase tracking-[0.14em] ${muted}`}>{m.id}</div>
                    <div className={`text-sm ${text}`}>{m.name}</div>
                  </Link>
                ))}
            </div>
          )}
        </aside>
      </main>
    </div>
  );
}
