import React from 'react';

export default function BoltzPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">
          Boltz: Structural Validation Engine
        </h1>
        <div className="prose max-w-none">
          <p className="text-lg text-gray-600 mb-6">
            The Boltz engine provides 3D structural validation and binding affinity prediction 
            for therapeutic designs generated by our AI platform.
          </p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-blue-900 mb-4">Key Features</h2>
            <ul className="list-disc list-inside text-blue-800 space-y-2">
              <li>Complex confidence scoring with structural integrity validation</li>
              <li>Binding affinity prediction for therapeutic-target interactions</li>
              <li>Multi-component validation for complex therapeutic systems</li>
              <li>Physical proof of mechanism with 3D binding confirmation</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
