/**
 * BM01 · evo2-e2e Target-Lock anchor panel.
 *
 * AUTO-GENERATED by scripts/anchor_extract/w2_extract_brm_evo2.py.
 * DO NOT hand-edit — re-run the script if the anchor repo changes.
 *
 * Every score comes from evo2-e2e/data/brain_met/pipeline_results_*.json,
 * which was produced by a real GPU run on Modal (crispro-evo2-v9 · A100).
 * We're serving the committed JSON as-is; no live Modal call at render time.
 *
 * User-facing narrative: `plainSummary` + `patientRelevance` are what the
 * persona reads first. The score table and validation metrics are the
 * pipeline-run backing behind that narrative.
 */
import type { BrmTargetLockPanel } from '../anchor-panel-types';

export const BM01_EVO2_PANEL: BrmTargetLockPanel = {
  plainSummary: 'CrisPRO ran evo2-e2e\'s 7-step brain-metastasis cascade on 29 genes — 20 known drivers plus 9 hard negatives — and scored every gene at every step. The pipeline separates real drivers from decoys with 0.96–1.00 AUROC across all 7 steps. Then CrisPRO looked up BM01\'s specific mutations against those results.',
  patientRelevance: 'BM01\'s TP53 R175H mutation is one of 13 clinical variants Evo2 has already scored on A100 GPUs — delta-LL = -0.418, flagged in the repo as \'BrM hotspot, 2× enriched.\' TP53 also lands in the top-3 targetable genes at both primary-tumor-escape and CNS-colonization steps (target-lock score 0.442 each). PIK3CA, BM01\'s likely secondary driver, tops the CNS-colonization ranking outright (target-lock score 0.320). These aren\'t hypothesis — they\'re peer-reviewable pipeline outputs with seed 42, ready for validation.',
  patientVariants: [
    {
      gene: 'PIK3CA',
      hgvsP: 'p.H1047R',
      deltaLL: -0.615,
      interpretation: 'Top penalized — PI3K kinase domain',
      relatedSteps: [
        'primary_tumor_escape',
        'cns_colonization',
      ],
      patientMatch: true,
    },
    {
      gene: 'TP53',
      hgvsP: 'p.R175H',
      deltaLL: -0.418,
      interpretation: 'BrM hotspot, 2× enriched (MSK-MET)',
      relatedSteps: [
        'primary_tumor_escape',
        'cns_colonization',
        'brain_niche_adaptation',
      ],
      patientMatch: true,
    },
    {
      gene: 'ESR1',
      hgvsP: 'p.D538G',
      deltaLL: -0.402,
      interpretation: 'Ligand-independent ER activation',
      relatedSteps: [
        'cns_colonization',
        'brain_niche_adaptation',
      ],
      patientMatch: false,
    },
    {
      gene: 'BACE1',
      hgvsP: 'p.D289N',
      deltaLL: 0.002,
      interpretation: 'Near-neutral hard negative — ACMG PVS1 context needed',
      relatedSteps: [
        'circulation_survival',
        'cns_colonization',
        'brain_niche_adaptation',
      ],
      patientMatch: false,
    },
  ],
  topTargetLock: [
    {
      gene: 'KMT2C',
      step: 'primary_tumor_escape',
      calibratedScore: 0.9625338996771026,
      targetLockScore: 0.552594133202869,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'TP53',
      step: 'primary_tumor_escape',
      calibratedScore: 0.914244282867128,
      targetLockScore: 0.4420860714544643,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'PIK3CA',
      step: 'primary_tumor_escape',
      calibratedScore: 0.8009286599547241,
      targetLockScore: 0.31964833516815416,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.55 (step=primary_tumor_escape not in primary_steps=[\'cns_colonization\'])',
      ],
    },
    {
      gene: 'KMT2C',
      step: 'intravasation',
      calibratedScore: 0.9761233290860287,
      targetLockScore: 0.30392677326157796,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.55 (step=intravasation not in primary_steps=[\'primary_tumor_escape\', \'cns_colonization\'])',
      ],
    },
    {
      gene: 'TWIST1',
      step: 'intravasation',
      calibratedScore: 0.8909408250458226,
      targetLockScore: 0.21500000000000002,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'MMP9',
      step: 'intravasation',
      calibratedScore: 0.7464545232056662,
      targetLockScore: 0.15863887628844672,
      label: true,
      bbbRelevant: true,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.55 (step=intravasation not in primary_steps=[\'primary_tumor_escape\', \'bbb_transit\'])',
      ],
    },
    {
      gene: 'BCL2',
      step: 'circulation_survival',
      calibratedScore: 0.9747649906698095,
      targetLockScore: 0.2499198592470343,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'BACE1',
      step: 'circulation_survival',
      calibratedScore: 0.8157558591854636,
      targetLockScore: 0.15596898023830022,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.55 (step=circulation_survival not in primary_steps=[\'cns_colonization\', \'brain_niche_adaptation\'])',
      ],
    },
    {
      gene: 'PIK3CA',
      step: 'circulation_survival',
      calibratedScore: 0.7758683911385501,
      targetLockScore: 0.14529469780370644,
      label: false,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.25 (step=circulation_survival not in primary_steps=[\'cns_colonization\'])',
      ],
    },
    {
      gene: 'CCL2',
      step: 'bbb_transit',
      calibratedScore: 0.9788708706896254,
      targetLockScore: 0.5248706879744958,
      label: true,
      bbbRelevant: true,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'MMP9',
      step: 'bbb_transit',
      calibratedScore: 0.8244290256328438,
      targetLockScore: 0.28843432052444856,
      label: true,
      bbbRelevant: true,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'MMP2',
      step: 'bbb_transit',
      calibratedScore: 0.8193498259208633,
      targetLockScore: 0.28485033495521195,
      label: true,
      bbbRelevant: true,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'PIK3CA',
      step: 'cns_colonization',
      calibratedScore: 0.9412831411248899,
      targetLockScore: 0.5811787912148257,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'KMT2C',
      step: 'cns_colonization',
      calibratedScore: 0.9294813718299385,
      targetLockScore: 0.552594133202869,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'TP53',
      step: 'cns_colonization',
      calibratedScore: 0.8607957858377869,
      targetLockScore: 0.4420860714544643,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'CCL2',
      step: 'brain_niche_adaptation',
      calibratedScore: 0.9732236949899097,
      targetLockScore: 0.5248706879744958,
      label: true,
      bbbRelevant: true,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'ESR1',
      step: 'brain_niche_adaptation',
      calibratedScore: 0.87853941601592,
      targetLockScore: 0.34622212957690246,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'SMARCA4',
      step: 'brain_niche_adaptation',
      calibratedScore: 0.8232256711835504,
      targetLockScore: 0.29749795311742966,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'VEGFA',
      step: 'brm_angiogenesis',
      calibratedScore: 0.993366357886901,
      targetLockScore: 0.4985852816213408,
      label: true,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
      ],
    },
    {
      gene: 'PIK3CA',
      step: 'brm_angiogenesis',
      calibratedScore: 0.657350930481019,
      targetLockScore: 0.14529469780370644,
      label: false,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.25 (step=brm_angiogenesis not in primary_steps=[\'cns_colonization\'])',
      ],
    },
    {
      gene: 'KMT2C',
      step: 'brm_angiogenesis',
      calibratedScore: 0.6372322733664324,
      targetLockScore: 0.13814853330071725,
      label: false,
      bbbRelevant: false,
      flags: [
        'Enformer disabled — chromatin score defaulted to 0.5',
        'mission_fit_discount=0.25 (step=brm_angiogenesis not in primary_steps=[\'primary_tumor_escape\', \'cns_colonization\'])',
      ],
    },
  ],
  validation: [
    {
      step: 'primary_tumor_escape',
      auroc: 0.9833,
      auprc: 0.9722,
      precisionAt3: 1.0,
      nPos: 9,
      nTotal: 29,
    },
    {
      step: 'intravasation',
      auroc: 0.9667,
      auprc: 0.9111,
      precisionAt3: 1.0,
      nPos: 5,
      nTotal: 29,
    },
    {
      step: 'circulation_survival',
      auroc: 0.9615,
      auprc: 0.8333,
      precisionAt3: 0.667,
      nPos: 3,
      nTotal: 29,
    },
    {
      step: 'bbb_transit',
      auroc: 0.974,
      auprc: 0.9481,
      precisionAt3: 1.0,
      nPos: 7,
      nTotal: 29,
    },
    {
      step: 'cns_colonization',
      auroc: 0.9952,
      auprc: 0.9958,
      precisionAt3: 1.0,
      nPos: 15,
      nTotal: 29,
    },
    {
      step: 'brain_niche_adaptation',
      auroc: 1.0,
      auprc: 1.0,
      precisionAt3: 1.0,
      nPos: 6,
      nTotal: 29,
    },
    {
      step: 'brm_angiogenesis',
      auroc: 1.0,
      auprc: 1.0,
      precisionAt3: 0.333,
      nPos: 1,
      nTotal: 29,
    },
  ],
  runInfo: {
    timestamp: '20260328T070235Z',
    seed: 42,
    disease: 'brain_met',
    fastMode: true,
    useEnformer: true,
    nGenes: 29,
    nPositives: 20,
    nNegatives: 9,
    nSteps: 7,
    elapsedSeconds: 157.9,
  },
  modalDeployments: [
    {
      service: 'Evo2 1B base (conditional LL)',
      app: 'crispro-evo2-v9',
      gpu: 'A100',
      status: 'LIVE',
    },
    {
      service: 'Enformer (chromatin accessibility)',
      app: 'crispro-enformer',
      gpu: 'T4',
      status: 'LIVE',
    },
    {
      service: 'BrM ICL adapter',
      app: 'brm-icl-v1',
      gpu: 'CPU',
      status: 'LIVE',
    },
  ],
  provenance: [
    {
      repo: 'evo2-e2e',
      sourcePath: 'data/brain_met/pipeline_results_20260328T070235Z.json',
      fileRole: 'Full BrM pipeline run — 7 steps × 29 genes',
    },
    {
      repo: 'evo2-e2e',
      sourcePath: 'data/brain_met/brm_clinical_variants.json',
      fileRole: '12 clinical variants — Evo2 input metadata',
    },
    {
      repo: 'evo2-e2e',
      sourcePath: 'README.md',
      fileRole: 'Evo2 conditional-LL scores for 4 named clinical variants (verbatim)',
    },
  ],
};
