/**
 * CRC01 · Brenus anchor evidence panel.
 *
 * AUTO-GENERATED by scripts/anchor_extract/w1_extract_crc_brenus.py.
 * DO NOT hand-edit — re-run the script if the anchor repo changes.
 *
 * Every field on this panel points back to a real committed file in the
 * Brenus repository (fjkiani/Brenus, snapshot as of the audit). No live
 * agent runs, no LLM calls at render time.
 *
 * User-facing narrative: `plainSummary` + `patientRelevance` are what the
 * persona reads first. The trial-card table and admissibility claims are
 * the audit backing behind that narrative.
 */
import type { CrcAnchorEvidencePanel } from '../anchor-panel-types';

export const CRC01_BRENUS_PANEL: CrcAnchorEvidencePanel = {
  plainSummary: 'CrisPRO pulled 42 real oncology trials from the Brenus engagement library and picked the two most relevant ones for a Lynch-syndrome / MSI-H colon patient like CRC01. Both are peer-reviewed, positive, and already used by Brenus as boundary evidence for immunotherapy-vs-chemotherapy decisions in this exact population.',
  patientRelevance: 'CRC01\'s MLH1 germline mutation makes her tumor mismatch-repair deficient — the exact biology KEYNOTE-177 selected for. That trial saw first-line pembrolizumab cut disease progression risk 40% versus chemotherapy. CheckMate-142 shows the flip side: in MSS colon cancer, CPI monotherapy responds at 0% — evidence that this benefit is MSI-H-specific, not general immunotherapy hype.',
  trials: [
    {
      nctId: 'NCT02563002',
      trialName: 'KEYNOTE-177',
      drug: 'Pembrolizumab vs. mFOLFOX6 or FOLFIRI ± bev/cetux',
      indication: '1L mCRC, MSI-H/dMMR only',
      cancerType: 'mCRC (MSI-H/dMMR)',
      line: '1L',
      phase: 'III',
      status: 'COMPLETED — POSITIVE',
      primaryResult: 'PFS HR 0.60; OS HR 0.74. Definitive positive for MSI-H.',
      primaryMet: 'YES (MSI-H only)',
      whyAppendix: 'MSI-H only — not applicable to 1L MSS CRC frame. Relevant to BreAK CRC-001 Arm 2A-2 context only.',
      program: 'IO_APPENDIX',
      dataStatus: 'VERIFIED',
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
        fileRole: 'Canonical Brenus trial-decode registry (v2)',
      },
    },
    {
      nctId: 'NCT02060188',
      trialName: 'CheckMate 142',
      drug: 'Nivolumab mono; nivo+ipi; MSS cohort enrolled separately',
      indication: 'Phase II multi-cohort; MSI-H and MSS cohorts',
      cancerType: 'mCRC (MSS + MSI-H)',
      line: '2L+',
      phase: 'II',
      status: 'COMPLETED',
      primaryResult: 'MSS cohort ORR 0% (n=74). MSI-H ORR 31% mono, 55% combo.',
      primaryMet: 'NO (MSS cohort)',
      whyAppendix: 'MSS cohort ORR 0% is a useful negative control but is monotherapy CPI only.',
      program: 'IO_APPENDIX',
      dataStatus: 'VERIFIED',
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
        fileRole: 'Canonical Brenus trial-decode registry (v2)',
      },
    },
  ],
  claims: [
    {
      claim: 'Brenus IO_APPENDIX role: 15-trial supporting IO corpus covering MSI-H positive controls, liver metastasis stratification evidence, vaccine T-cell pharmacodynamic dissociation, and the ongoing Phase III landscape — providing the full boundary conditions for IO benefit in CRC.',
      admissibility: 'T1-CORP',
      verified: true,
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/program_assets/program_asset_io_appendix.json',
        fileRole: 'IO appendix program asset — Brenus positioning artifact',
      },
    },
    {
      claim: 'KEYNOTE-177 primary read-out (Brenus VERIFIED): PFS HR 0.60; OS HR 0.74. Definitive positive for MSI-H.',
      admissibility: 'T1-SCI',
      verified: true,
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
        fileRole: 'Trial-decode registry v2 · KEYNOTE-177 entry',
      },
    },
    {
      claim: 'CheckMate-142 MSS-vs-MSI-H boundary (Brenus VERIFIED): MSS cohort ORR 0% (n=74). MSI-H ORR 31% mono, 55% combo.',
      admissibility: 'T1-SCI',
      verified: true,
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
        fileRole: 'Trial-decode registry v2 · CheckMate-142 entry',
      },
    },
    {
      claim: '2 additional Brenus-decoded trials contain MSS + MSI-H mixed cohorts (used as boundary conditions for the BreAK CRC-001 MSS engagement).',
      admissibility: 'T1-CORP',
      verified: true,
      source: {
        repo: 'Brenus',
        sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
        fileRole: 'Aggregate over trial-decode registry v2',
      },
    },
  ],
  adjacentEngagementNote: 'These trials sit in Brenus\'s IO_APPENDIX bucket — Brenus\'s primary engagement is with an MSS colon-cancer vaccine (BreAK CRC-001). KEYNOTE-177 and CheckMate-142 are the boundary conditions that define where that MSS program does NOT apply. For CRC01 (MSI-H), those boundary conditions are the primary evidence.',
  provenance: [
    {
      repo: 'Brenus',
      sourcePath: 'engagements/brenus/trial_intelligence/trial_decode_registry_v2.json',
      fileRole: 'Trial-decode registry v2 (42 trials)',
    },
    {
      repo: 'Brenus',
      sourcePath: 'engagements/brenus/trial_intelligence/program_assets/program_asset_io_appendix.json',
      fileRole: 'IO appendix program-asset',
    },
  ],
};
