import React from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Download } from 'lucide-react';

// Helper function to sanitize colors for html2canvas
const sanitizeColor = (color: string): string => {
  if (!color) return '#cbd5e1';

  // Handle HSL colors by converting to hex
  if (color.startsWith('hsl')) {
    // Simple HSL to hex conversion for common cases
    if (color.includes('210')) return '#06b6d4'; // Cyan
    if (color.includes('220')) return '#3b82f6'; // Blue
    return '#cbd5e1'; // Default fallback
  }

  // Handle CSS custom properties (variables)
  if (color.startsWith('var(')) {
    return '#cbd5e1'; // Default fallback for CSS variables
  }

  // Handle rgb/rgba colors
  if (color.startsWith('rgb')) {
    // For now, just use fallback - could add rgb to hex conversion
    return '#cbd5e1';
  }

  // Return hex colors as-is
  if (color.startsWith('#')) {
    return color;
  }

  // Default fallback for any unsupported format
  return '#cbd5e1';
};

// --- SIMPLE PDF EXPORT USING jsPDF ---
// This captures the current slide and converts it to PDF
export const exportCurrentSlideToPDF = async (slideTitle: string = 'Slide') => {
  try {
    console.log('Starting PDF export...');

    // Find the current slide content
    const slideElement = document.querySelector('[data-slide-content="true"]') ||
                        document.querySelector('.slide-content') ||
                        document.querySelector('section') ||
                        document.body;

    if (!slideElement) {
      console.error('No slide content found');
      alert('Could not find slide content to export');
      return;
    }

    console.log('Found slide element:', slideElement);

    // Clone the element to avoid modifying the original
    const clonedElement = slideElement.cloneNode(true) as HTMLElement;

    // Sanitize colors in the cloned element
    const allElements = clonedElement.querySelectorAll('*');
    allElements.forEach(el => {
      const style = getComputedStyle(el);
      if (style.color && style.color !== 'inherit') {
        (el as HTMLElement).style.color = sanitizeColor(style.color);
      }
      if (style.backgroundColor && style.backgroundColor !== 'rgba(0, 0, 0, 0)') {
        (el as HTMLElement).style.backgroundColor = sanitizeColor(style.backgroundColor);
      }
    });

    // Temporarily append to body for rendering
    clonedElement.style.position = 'absolute';
    clonedElement.style.left = '-9999px';
    clonedElement.style.top = '-9999px';
    clonedElement.style.width = '1200px';
    clonedElement.style.height = '675px';
    document.body.appendChild(clonedElement);

    // Use html2canvas to capture the slide with better settings
    const canvas = await html2canvas(clonedElement, {
      scale: 2, // Higher quality
      useCORS: true,
      allowTaint: false, // Disable taint for better compatibility
      backgroundColor: '#1e293b', // Match your dark theme
      width: 1200,
      height: 675,
      logging: false, // Disable logging for cleaner output
      ignoreElements: (element) => {
        // Ignore navigation controls and other UI elements
        return element.classList.contains('navigation-controls') ||
               element.classList.contains('brand') ||
               element.classList.contains('slide-counter');
      }
    });

    // Remove the cloned element
    document.body.removeChild(clonedElement);

    console.log('Canvas created, dimensions:', canvas.width, 'x', canvas.height);

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [canvas.width, canvas.height]
    });

    // Add the captured image to PDF
    const imgData = canvas.toDataURL('image/png', 0.95); // Higher quality
    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);

    // Add title and branding
    pdf.setFontSize(16);
    pdf.setTextColor(255, 255, 255);
    pdf.text(slideTitle, 20, 30);

    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.text('Generated by CrisPRO.ai', 20, canvas.height - 20);

    // Save the PDF
    const fileName = `${slideTitle.replace(/\s+/g, '_').toLowerCase()}_slide.pdf`;
    pdf.save(fileName);

    console.log('PDF saved successfully:', fileName);
    alert(`PDF saved as: ${fileName}`);

  } catch (error) {
    console.error('PDF Export Error:', error);
    alert('Error creating PDF: ' + error.message);
  }
};

// --- PDF DOWNLOAD BUTTON COMPONENT ---
interface SimplePDFDownloadProps {
  title?: string;
  buttonText?: string;
  className?: string;
}

export const SimplePDFDownloadButton = ({
  title = 'Current Slide',
  buttonText = 'Download PDF',
  className = ''
}: SimplePDFDownloadProps) => {
  const [isGenerating, setIsGenerating] = React.useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      await exportCurrentSlideToPDF(title);
    } catch (error) {
      console.error('Download failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className={`inline-flex items-center justify-center px-4 py-2 bg-blue-500/20 text-blue-400 hover:bg-blue-500/30 border border-blue-500/30 rounded-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
      title="Download current slide as PDF"
    >
      <Download size={18} className="mr-2" />
      <span>{isGenerating ? 'Generating...' : buttonText}</span>
    </button>
  );
};

// --- FULL PRESENTATION PDF EXPORT ---
export const exportAllSlidesToPDF = async (slides: any[], presentationTitle: string = 'Presentation') => {
  try {
    console.log('Starting full presentation PDF export...');
    console.log('Number of slides:', slides?.length);

    if (!slides || slides.length === 0) {
      throw new Error('No slides found to export');
    }

    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [1200, 675]
    });

    // For full presentation, we'll create a simple template-based PDF
    // since the slides are React components, not data objects
    const slideTitles = [
      'S/P/E Framework Overview',
      'The Achievement Gap',
      'For Clinicians',
      'For Biotechs',
      'Chemotherapy Challenges',
      'The Guidance Engine',
      'S/P/E Framework Details',
      'Trustworthy Evidence Doctrine',
      'Multiple Myeloma Case',
      'Ovarian Cancer Study',
      'Melanoma Case Study',
      'Benchmark Results',
      'The Logic Flow'
    ];

    for (let i = 0; i < slides.length; i++) {
      if (i > 0) {
        pdf.addPage();
      }

      // Create a simple template for each slide
      const slideTitle = slideTitles[i] || `Slide ${i + 1}`;

      // Add background (simulated by adding a filled rectangle)
      pdf.setFillColor(30, 41, 59); // #1e293b
      pdf.rect(0, 0, 1200, 675, 'F');

      // Add title
      pdf.setFontSize(48);
      pdf.setTextColor(6, 182, 212); // #06b6d4
      const titleWidth = pdf.getTextWidth(slideTitle);
      const titleX = (1200 - titleWidth) / 2;
      pdf.text(slideTitle, titleX, 200);

      // Add subtitle or description
      pdf.setFontSize(24);
      pdf.setTextColor(148, 163, 184); // #94a3b8
      const subtitle = `Part of the S/P/E Framework Presentation`;
      const subtitleWidth = pdf.getTextWidth(subtitle);
      const subtitleX = (1200 - subtitleWidth) / 2;
      pdf.text(subtitle, subtitleX, 280);

      // Add page number and branding
      pdf.setFontSize(12);
      pdf.setTextColor(100, 116, 139);
      pdf.text(`Page ${i + 1} of ${slides.length}`, 20, 650);
      pdf.text('Generated by CrisPRO.ai', 1050, 650);

      console.log(`Added slide ${i + 1}: ${slideTitle}`);
    }

    const fileName = `${presentationTitle.replace(/\s+/g, '_').toLowerCase()}_presentation.pdf`;
    pdf.save(fileName);

    console.log('Full presentation PDF saved successfully:', fileName);
    alert(`Full presentation PDF saved as: ${fileName}`);

  } catch (error) {
    console.error('Full PDF Export Error:', error);
    alert('Error creating full presentation PDF: ' + error.message);
  }
};

// --- FULL PRESENTATION PDF DOWNLOAD BUTTON ---
interface FullPDFDownloadProps {
  slides: any[];
  presentationTitle?: string;
  buttonText?: string;
  className?: string;
}

export const FullPDFDownloadButton = ({
  slides,
  presentationTitle = 'Presentation',
  buttonText = 'Download Full PDF',
  className = ''
}: FullPDFDownloadProps) => {
  const [isGenerating, setIsGenerating] = React.useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      await exportAllSlidesToPDF(slides, presentationTitle);
    } catch (error) {
      console.error('Download failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className={`inline-flex items-center justify-center px-4 py-2 bg-purple-500/20 text-purple-400 hover:bg-purple-500/30 border border-purple-500/30 rounded-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
      title="Download full presentation as PDF"
    >
      <Download size={18} className="mr-2" />
      <span>{isGenerating ? 'Generating...' : buttonText}</span>
    </button>
  );
};
