// AUTO-GENERATED by w-research-kb.py — knowledge base chapters
export type KBChapter = {
  slug: string;
  num: number;
  title: string;
  eyebrow: string;
  body: string[];
};

export const KB_CHAPTERS: KBChapter[] = [
  {
    slug: 'why-trials-fail',
    num: 1,
    title: 'Why Phase III oncology trials still fail on responders',
    eyebrow: 'Foundational',
    body: [
    'Failed pivotal oncology trials are rarely failed drugs. In the public ledger, every failed program still has a responder subgroup — the split shows up on the mechanism axis, not on the histology label.',
    'This chapter frames the mechanism-alignment problem: why unstratified populations wash out real signal, and why survivor bias inside surviving programs is the mirror image of that same misalignment.',
  ],
  },
  {
    slug: 'mechanism-alignment-layer',
    num: 2,
    title: 'The mechanism-alignment layer',
    eyebrow: 'Architecture',
    body: [
    'Above every histology label and every companion-diagnostic test sits a mechanism layer — the actual biology a therapy operates on. CrisPRO occupies that layer as infrastructure.',
    'This chapter defines the layer, contrasts it with the three comparator classes (histology, comprehensive genomic profiling, real-world evidence), and explains what changes when a decision is made against a mechanism vector instead of a label.',
  ],
  },
  {
    slug: 'eight-dimensional-vector',
    num: 3,
    title: 'The eight-dimensional patient vector',
    eyebrow: 'Method',
    body: [
    'The patient vector p = [ddr, mapk, pi3k, vegf, her2, io, efflux, rss] lives in the unit cube. Each axis compresses one mechanism family from molecular profiling.',
    'This chapter walks the axes without naming a specific program — what each dimension measures, what evidence supports it, and where the axis is silent.',
  ],
  },
  {
    slug: 'trial-vector-library',
    num: 4,
    title: 'Trial-vector library — the other half of the equation',
    eyebrow: 'Method',
    body: [
    'A patient vector is only half the comparison. Every trial in the ledger is encoded as a trial vector — the mechanism configuration that trial is really testing, extracted from eligibility, arms, and endpoints.',
    'This chapter defines the vector schema, how ranges become vectors, and how conflicting arms are resolved.',
  ],
  },
  {
    slug: 'mechanism-fit-engine',
    num: 5,
    title: 'The mechanism-fit engine',
    eyebrow: 'Method',
    body: [
    'Given a patient vector p and a trial vector t, the mechanism-fit engine returns a scalar in [0,1]. The formula is locked and reproducible; it is not the point. The point is that the same operator ranks every patient against every trial.',
    'This chapter shows what the engine does and does not do — no free parameters, no post-hoc tuning, no leaderboard chasing.',
  ],
  },
  {
    slug: 'target-lock',
    num: 6,
    title: 'Target-lock — identifying the driver, not the label',
    eyebrow: 'Method',
    body: [
    'Before mechanism fit is meaningful, we must know which metastasis-driving axis a program is actually asking about. Target-lock is that step.',
    'This chapter defines the eight-step target identification loop and the guardrails that prevent target-drift once a program is locked.',
  ],
  },
  {
    slug: 'sl-therapy-bridge',
    num: 7,
    title: 'Synthetic-lethality therapy bridge',
    eyebrow: 'Method',
    body: [
    'Two mechanism axes rarely act alone. The SL bridge encodes allow / warn / disallow rules over combination therapy space, so a mechanism-aligned patient does not get paired with a mechanistically incompatible partner.',
    'This chapter defines the allow-warn-disallow layer and how the bridge stays reproducible across programs.',
  ],
  },
  {
    slug: 'biomarker-taxonomy',
    num: 8,
    title: 'Biomarker taxonomy — six domains',
    eyebrow: 'Reference',
    body: [
    'Biomarkers are not one thing. Across the ledger they cluster into six domains: DNA damage response, mitogenic signaling, immune context, tumor microenvironment, metabolic/efflux, and replication-stress.',
    'This chapter maps each domain to the eight-dimensional axis it participates in, and calls out where the mapping is one-to-one and where it is not.',
  ],
  },
  {
    slug: 'escape-map',
    num: 9,
    title: 'EscapeMap — when the mechanism moves',
    eyebrow: 'Method',
    body: [
    'Some mechanism axes do not stay put — tumors escape. EscapeMap is the sub-engine that tracks which axes are labile and how a program should watch them post-selection.',
    'This chapter defines the escape-map methodology at the categorical level, without naming a specific program.',
  ],
  },
  {
    slug: 'two-gate-selection',
    num: 10,
    title: 'Two-gate patient selection',
    eyebrow: 'Framework',
    body: [
    'Selection is not one test. In every deployed program it is two gates: the first gate qualifies a patient for a mechanism, the second gate confirms the driver is still the one the trial is asking about.',
    'This chapter defines the two-gate schema and the failure modes when either gate is skipped.',
  ],
  },
  {
    slug: 'holistic-score',
    num: 11,
    title: 'Holistic score — beyond fit alone',
    eyebrow: 'Method',
    body: [
    'Mechanism fit is necessary but not sufficient. The holistic score combines fit with feasibility, safety, and expected-benefit priors into a single reproducible operator.',
    'This chapter defines the components and the freezing rules that prevent post-hoc tuning.',
  ],
  },
  {
    slug: 'governance-guardrails',
    num: 12,
    title: 'Governance guardrails — the 8D framework',
    eyebrow: 'Governance',
    body: [
    'Every claim in the ledger and every claim on this site is anchored to source material and reproducible from a fixed formula. That is the 8D framework: eight discipline checks, applied at every step.',
    'This chapter enumerates the eight checks — admissibility, retained-safe aggregation, forbidden-string audit, formula-lock, reproducibility, source-attribution, versioning, and receipts.',
  ],
  },
  {
    slug: 'public-ledger',
    num: 13,
    title: 'The public ledger',
    eyebrow: 'Deliverable',
    body: [
    'Every program CrisPRO has decoded lives in the public ledger. Seven programs, forty-two trials, decoded before we open a sales conversation.',
    'This chapter explains why the ledger is public, what stays in it, and what never enters it.',
  ],
  },
  {
    slug: 'roadmap',
    num: 14,
    title: 'Roadmap — from decoded programs to the alignment layer',
    eyebrow: 'Roadmap',
    body: [
    'The endpoint is not a study. It is a callable mechanism-alignment layer — a BD API, an alignment gate, a reader — that any sponsor can consume.',
    'This chapter defines the sequenced deliverables and the retained-safe milestones.',
  ],
  },
];

export function getChapter(slug: string): KBChapter | undefined {
  return KB_CHAPTERS.find((c) => c.slug === slug);
}
