// AUTO-GENERATED by w-research-kb.py — knowledge base index
export type KBModule = {
  id: string;
  slug: string;
  name: string;
  type: string;
  oneLiner: string;
  chapterSlug: string;
};

export type KBCapability = {
  slug: string;
  code: string;
  name: string;
  oneLiner: string;
};

export const KB_MODULES: KBModule[] = [
  {
    id: 'MOD-01',
    slug: 'stratification-anatomic',
    name: 'Anatomic-site stratification',
    type: 'patient_stratification',
    oneLiner: 'Stratify enrollment by the anatomic-site variable that most disturbs the mechanism signal.',
    chapterSlug: 'two-gate-selection',
  },
  {
    id: 'MOD-02',
    slug: 'stratification-tmb',
    name: 'Tumor-mutation-burden enrichment',
    type: 'patient_stratification',
    oneLiner: 'Enrich for the burden threshold where mechanism signal becomes reliable.',
    chapterSlug: 'two-gate-selection',
  },
  {
    id: 'MOD-03',
    slug: 'stratification-driver-subtype',
    name: 'Driver-mutation subtype ranking',
    type: 'patient_stratification',
    oneLiner: 'Rank patients within a driver-mutation class by subtype rather than by the class alone.',
    chapterSlug: 'target-lock',
  },
  {
    id: 'MOD-04',
    slug: 'stratification-ctdna',
    name: 'Baseline ctDNA / disease burden',
    type: 'patient_stratification',
    oneLiner: 'Fold circulating-DNA disease burden into the eight-dimensional vector at baseline.',
    chapterSlug: 'eight-dimensional-vector',
  },
  {
    id: 'MOD-05',
    slug: 'stratification-immune',
    name: 'Immune-context baseline',
    type: 'patient_stratification',
    oneLiner: 'Encode CD8+/regulatory context into the io axis at baseline.',
    chapterSlug: 'eight-dimensional-vector',
  },
  {
    id: 'MOD-06',
    slug: 'trial-design-arm-balance',
    name: 'Arm-balance check',
    type: 'trial_design',
    oneLiner: 'Detect mechanism-drift between arms before the trial locks — not after.',
    chapterSlug: 'trial-vector-library',
  },
  {
    id: 'MOD-07',
    slug: 'trial-design-endpoint-fit',
    name: 'Endpoint-mechanism fit',
    type: 'trial_design',
    oneLiner: 'Ensure the endpoint measures the mechanism the trial is actually testing.',
    chapterSlug: 'mechanism-fit-engine',
  },
  {
    id: 'MOD-08',
    slug: 'trial-design-eligibility',
    name: 'Eligibility-vector diagnostic',
    type: 'trial_design',
    oneLiner: 'Convert eligibility criteria into a vector and flag the axes the criteria are silent on.',
    chapterSlug: 'trial-vector-library',
  },
  {
    id: 'MOD-09',
    slug: 'bd-lookalike',
    name: 'Look-alike program search',
    type: 'bd_intelligence',
    oneLiner: 'Find the historical programs whose trial vector is closest to a candidate program.',
    chapterSlug: 'public-ledger',
  },
  {
    id: 'MOD-10',
    slug: 'bd-failure-decoder',
    name: 'Trial-failure decode',
    type: 'bd_intelligence',
    oneLiner: 'Post-hoc decode of a failed pivotal trial into mechanism-aligned responder / non-responder splits.',
    chapterSlug: 'why-trials-fail',
  },
  {
    id: 'MOD-11',
    slug: 'target-lock-loop',
    name: 'Eight-step target-lock loop',
    type: 'target_identification',
    oneLiner: 'The eight-step loop that anchors a program to the correct metastasis-driving axis.',
    chapterSlug: 'target-lock',
  },
  {
    id: 'MOD-12',
    slug: 'sl-combination-mapper',
    name: 'SL combination mapper',
    type: 'combination_therapy',
    oneLiner: 'Map candidate combinations against the allow/warn/disallow rules of the SL bridge.',
    chapterSlug: 'sl-therapy-bridge',
  },
  {
    id: 'MOD-13',
    slug: 'escapemap-monitor',
    name: 'EscapeMap monitor',
    type: 'post_selection',
    oneLiner: 'Watch the axes known to be labile after a mechanism-aligned selection is made.',
    chapterSlug: 'escape-map',
  },
  {
    id: 'MOD-14',
    slug: 'governance-audit',
    name: 'Governance-audit checklist',
    type: 'governance',
    oneLiner: 'Eight-check discipline audit applied at every claim, every commit, every report.',
    chapterSlug: 'governance-guardrails',
  },
  {
    id: 'MOD-15',
    slug: 'brief-generator',
    name: 'BRIEF program asset generator',
    type: 'deliverable',
    oneLiner: 'Compile a mechanism-aligned program brief from ledger, capability, and module state.',
    chapterSlug: 'roadmap',
  },
];

export const KB_CAPABILITIES: KBCapability[] = [
  {
    slug: 'patient-vector',
    code: 'CAP-01',
    name: '8-D patient biology vector',
    oneLiner: 'Multi-modal molecular profiles compressed into an eight-dimensional vector we can compare against trials.',
  },
  {
    slug: 'mechanism-fit',
    code: 'CAP-02',
    name: 'Mechanism-fit engine',
    oneLiner: 'Ranks any trial against any patient by mechanism alignment on the eight-dimensional axis.',
  },
  {
    slug: 'trial-vector',
    code: 'CAP-03',
    name: 'Trial vector library',
    oneLiner: 'Every eligibility criterion, arm, and endpoint reduced to a mechanism vector for comparison.',
  },
  {
    slug: 'target-lock',
    code: 'CAP-04',
    name: 'Target-lock',
    oneLiner: 'Identifies the metastasis driver a program is actually asking about, before selection.',
  },
  {
    slug: 'sl-bridge',
    code: 'CAP-05',
    name: 'Synthetic-lethality bridge',
    oneLiner: 'Allow/warn/disallow logic that connects mechanism vectors to combination-therapy space.',
  },
];

export function getModule(slug: string): KBModule | undefined {
  return KB_MODULES.find((m) => m.slug === slug);
}

export function getCapability(slug: string): KBCapability | undefined {
  return KB_CAPABILITIES.find((c) => c.slug === slug);
}
