/**
 * pipeline-master-persona-copy.ts
 *
 * D15 persona overlay side-car for pipeline-master.ts.
 *
 * WHY A SIDE-CAR:
 *   pipeline-master.ts is generated by the W2 codemod from
 *   crispro_master_pipeline.json. Adding personaCopy fields inline would
 *   either couple the generator to persona logic (larger scope) or be
 *   blown away on the next regeneration. Instead this file carries the
 *   overlay in a parallel structure keyed by `program_id`.
 *
 * WHAT IT COVERS (D15 first pass):
 *   Program-header copy only — program_name, headline, indication_focus,
 *   ip_value, admissibility. Persona-varied strings for `patient` and
 *   `pharma`; the English root in pipeline-master.ts is the oncologist
 *   baseline by design.
 *
 * WHAT IT DOES NOT COVER (deferred):
 *   Program-level key_findings, transfer_lessons, and trial-level
 *   primary_result / outcome / failure_mode. These carry dense cited
 *   statistical evidence (HR / OS / PFS / PMIDs / p-values) — adapting
 *   them to plain-English patient framing risks losing the numeric
 *   precision the audit trail depends on. That pass gets its own chunk
 *   if the reviewer signs off on the interpretation risk.
 *
 * READ SITES:
 *   import { getPipelinePersonaHeader } from '@/data/pipeline-master-persona-copy';
 *   const header = getPipelinePersonaHeader(program.program_id, persona);
 *   // Returns program-header fields with persona-appropriate voice, or
 *   // falls back to the English root fields from the passed-in program.
 */

import type { Persona } from '@/context/PersonaContext';
import type { PipelineProgram } from './pipeline-master';

export interface PipelineProgramCopyFields {
  program_name: string;
  headline: string;
  indication_focus: string;
  ip_value: string;
  admissibility: string;
}

export type PipelineProgramPersonaOverlay = Partial<
  Record<Persona, Partial<PipelineProgramCopyFields>>
>;

/**
 * Persona overlay keyed by program_id. Populated for the 7 programs
 * currently in pipeline-master.ts. Add new keys here when the codemod
 * emits new programs.
 */
export const PIPELINE_PROGRAM_PERSONA_COPY: Record<string, PipelineProgramPersonaOverlay> = {
  ATR_DDR: {
    patient: {
      program_name: 'Trials of DNA-repair-blocking drugs that failed',
      headline:
        'Five clinical trials tested drugs that block a cancer’s DNA-repair machinery. On paper each trial looked like a failure — the tumors overall did not respond. But when we look inside each trial, there are specific patients who DID respond very well. The pattern: the trials enrolled the wrong patients. In each trial there is a specific patient signal (a biomarker) that the trial should have used to pick who to enroll. Without that filter, the responders got hidden in a bigger group of non-responders.',
      indication_focus:
        'Ovarian cancer (three trials), non-small-cell lung cancer (one trial), and mixed solid tumors (one trial) — all testing drugs that block a specific DNA-repair enzyme called ATR, or a related one called WEE1, in tumors with weakened DNA repair.',
      ip_value:
        'This is the graveyard set — six trials representing about $1.95 billion in failed drug-program investment. It shows how a better patient-picking rule would have saved a real fraction of that money.',
    },
    pharma: {
      program_name: 'ATR/DDR franchise-failure corpus',
      headline:
        'Five-trial ATR/DDR franchise-failure corpus with decoded selection-failure modes — identifies the biomarker gate that all three completed trials missed and the responder subpopulations hidden inside each ITT-failure read. Audit-trail-grade franchise substrate call.',
      indication_focus:
        'Ovarian (3), NSCLC (1), mixed solid tumors (1) — ATR and WEE1 inhibitor franchises in DDR-deficient substrate populations.',
      ip_value:
        'GLB set — six-trial IP-valuation graveyard corpus. ATR/DDR contributes 4 of 6 GLB trials. Estimated decoded franchise value: $1.95B in failed program investment. Franchise-audit anchor for ATR/DDR substrate re-underwrite.',
    },
  },

  CEACAM5: {
    patient: {
      program_name: 'Why drugs aimed at the CEACAM5 marker have been failing',
      headline:
        'Five clinical trials in patients tried to hit a tumor marker called CEACAM5 with different kinds of drugs. All five failed. The pattern that comes out: the test used to pick patients was picking too many people. When the test bar is raised, only patients with very high CEACAM5 on the tumor, a signal starts to appear. This corpus explains why the earlier trials could not find that signal.',
      indication_focus:
        'Failed CEACAM5 drug trials in second-line non-small-cell lung cancer (one Phase III), third-line-or-later metastatic colon cancer (three trials), and other solid tumors including colon cancer (one Phase I paused in Europe over safety).',
      ip_value:
        'The two-step patient-picking rule for CEACAM5 (only patients whose tumors have very high CEACAM5 AND whose tumors look immune-friendly enough) is what this corpus explains. It anchors the pitch to Sanofi on the SAR445953 and SAR445877 programs.',
    },
    pharma: {
      program_name: 'CEACAM5 franchise-failure corpus',
      headline:
        'Five-trial CEACAM5 franchise-failure corpus spanning ADC (DM4, SN-38, Topo1i payloads), CEA-TCB bispecific, and EU-hold safety class-signal. Includes IHC-threshold audit, CRC-transfer read, and the audit-trail-grade finding that CEACAM5 IHC is prognostic, not predictive.',
      indication_focus:
        '2L+ NSCLC (1 Phase III), 3L+ mCRC (3 trials), advanced solid tumors including CRC (1 Phase I on EU clinical hold) — pan-histology CEACAM5 franchise footprint.',
      ip_value:
        'Sanofi franchise pitch anchor. Two-gate patient-selection framework (CEACAM5 IHC ≥80% + IO permissiveness) applied to SAR445953 and SAR445877 CDx pathway. Franchise-audit receipt on the trail.',
    },
  },

  IO_CORE: {
    patient: {
      program_name: 'Why immunotherapy has not worked for the common form of colon cancer',
      headline:
        'Immunotherapy has been a big success for many cancers — but for the most common kind of colon cancer, called MSS, it usually does not work. Seven clinical trials tried different ways to fix that, and most of them failed. Looking at all seven together, three specific conditions matter for a patient to benefit: their cancer must NOT have spread to the liver, the tumor must carry a lot of mutations (a blood-test signal called pTMB above 28), and the tumor must already look immune-active on examination. Without those three, immunotherapy in this cancer is unlikely to help.',
      indication_focus:
        'Failed immunotherapy trials for the common (MSS/pMMR) form of colon cancer that has spread — across first-line, later-line, and refractory settings. Includes vaccine, checkpoint-inhibitor, MEK-inhibitor combos, and multi-drug immunotherapy combinations.',
      ip_value:
        'This is the primary comparator library for the active vaccine trial partner. It defines the three conditions under which immunotherapy CAN work in MSS colon cancer, and the four design gaps in the current vaccine trial.',
    },
    pharma: {
      program_name: 'MSS mCRC IO franchise-failure corpus',
      headline:
        'Seven-trial MSS mCRC IO franchise-failure corpus — audit-trail-grade evidence base for MSS-CRC IO non-response, with three franchise-fit conditions extracted from convergent trial evidence: non-liver-metastatic anatomy, pTMB ≥28 gate, and immune-inflamed TME substrate.',
      indication_focus:
        '1L through refractory MSS/pMMR mCRC across 7 trials — vaccine, CPI, MEKi+CPI, and combination IO strategies. Pan-line-of-therapy IO franchise footprint.',
      ip_value:
        'Primary comparator corpus for the active 1L MSS mCRC vaccine franchise engagement. Defines the three franchise-fit conditions for IO benefit in MSS CRC and the four design-gap-derisk items on the active franchise audit trail.',
    },
  },

  IO_APPENDIX: {
    patient: {
      program_name: 'Supporting evidence for what does and does not work with immunotherapy in colon cancer',
      headline:
        'Fifteen additional colon-cancer trials that fill in the picture around immunotherapy. Some are positive controls (trials in the rarer MSI-high type where immunotherapy DOES work). Others explore the liver-metastasis question in more detail, the disconnect between what a vaccine does to blood immune cells versus what happens inside the tumor, and combinations with other drugs. Together with the core failure corpus, this gives the full map of when immunotherapy in colon cancer is likely to help.',
      indication_focus:
        'Colon cancer across all treatment lines and both MSI types. Includes trials where immunotherapy works (MSI-high controls), trials that show how the location of the tumor’s spread matters, vaccine trials where the immune system responded in blood but not in the tumor, and combinations with TGF-β or VEGF blockers.',
      ip_value:
        'Supporting evidence for the design-gap review of the active vaccine trial partner, and for the three conditions under which immunotherapy CAN work in this cancer.',
    },
    pharma: {
      program_name: 'MSS CRC IO franchise-supporting evidence corpus',
      headline:
        '15-trial IO franchise-supporting corpus — boundary conditions for IO in CRC: MSI-H positive-control franchises, liver-metastasis stratification receipts, vaccine-PD-dissociation audit, TGF-β/VEGF combo franchise reads, and the ongoing Phase III landscape.',
      indication_focus:
        'CRC across all treatment lines and MSI status. Includes MSI-H positive-control franchises (KEYNOTE-177, CheckMate 142), liver-metastasis stratification substrate, vaccine-PD-dissociation audit, TGF-β/VEGF combo franchises, and ongoing Phase III (STELLAR-303).',
      ip_value:
        'Franchise-audit supporting evidence for the active 1L MSS mCRC vaccine engagement’s design-gap read, and for the three franchise-fit conditions for IO benefit in MSS CRC.',
    },
  },

  HISTORICAL_BENCHMARKS: {
    patient: {
      program_name: 'How well standard chemotherapy already works in this cancer',
      headline:
        'Six trials in the same kind of colon cancer, all using the standard chemotherapy of the field (called mFOLFOX6, sometimes with an added drug called bevacizumab). These trials tell us the current baseline — how long patients typically live, how often the tumor shrinks, how long the treatment holds. Any new drug added to this chemotherapy has to beat these numbers to matter.',
      indication_focus:
        'The standard chemotherapy backbone (mFOLFOX6, sometimes with bevacizumab) tested in first-line MSS colon cancer that has spread.',
      ip_value:
        'The control-arm reference point for any first-line MSS colon-cancer trial that adds a new drug to standard chemotherapy — including the active vaccine engagement.',
    },
    pharma: {
      program_name: 'mFOLFOX6 ± bev backbone benchmark set',
      headline:
        'Six-entry mFOLFOX6 ± bevacizumab backbone benchmark set — control-arm expectations for the BreAK CRC-001 franchise engagement and for any 1L MSS mCRC trial adding an investigational agent to standard chemotherapy backbone. Franchise-audit-grade benchmark set.',
      indication_focus:
        'mFOLFOX6 ± bevacizumab benchmark set for 1L MSS mCRC franchise footprint.',
      ip_value:
        'Control-arm expectation reference for any 1L MSS mCRC franchise trial adding an investigational agent to standard chemotherapy backbone — franchise-audit anchor for backbone-competition risk.',
    },
  },

  BREAK_CRC_001: {
    patient: {
      program_name: 'BreAK CRC-001 — live vaccine trial in first-line colon cancer',
      headline:
        'BreAK CRC-001 is an active Phase I/II trial testing an experimental vaccine (STC-1010, a treated-whole-cell vaccine) in first-line MSS colon cancer. CrisPRO is providing the mechanism-alignment read on this trial — checking whether the biology of the design is likely to work, listing the four biggest risks in the design, and comparing it against 22 other trials in the same space.',
      indication_focus:
        'First-line MSS colon cancer that has spread — an active partner trial.',
      ip_value:
        'A live engagement. The value CrisPRO brings is the mechanism-alignment layer applied to an active vaccine program — does the trial design make biological sense, what should be added, what should be dropped.',
    },
    pharma: {
      program_name: 'BreAK CRC-001 — active franchise-engagement asset',
      headline:
        'BreAK CRC-001 — active Phase I/II trial of STC-1010 (DNFB-haptenated whole-cell vaccine) in 1L MSS mCRC, with CrisPRO mechanism-fit read, four-gap design-risk inventory, and 22-trial franchise comparator context. Franchise-audit-grade engagement.',
      indication_focus:
        '1L MSS/pMMR mCRC franchise footprint — live engagement.',
      ip_value:
        'Active franchise engagement anchored on the CrisPRO mechanism-alignment audit layer applied to a live 1L MSS mCRC vaccine franchise. Franchise-audit-grade receipt trail.',
    },
  },

  GBM_ESCAPEMAP: {
    patient: {
      program_name: 'GBM EscapeMap — checking whether a specific escape route explains why brain-cancer treatment stops working',
      headline:
        'GBM EscapeMap looked at whether a specific tumor-cell change (called ZEB1 activation, part of a switch called EMT) is what makes glioblastoma — the most common aggressive brain cancer — stop responding to the standard treatment (Stupp: temozolomide + radiation). The hypothesis was tested across three independent datasets. Answer: no, this specific hypothesis did NOT hold up across all three.',
      indication_focus:
        'Recurrent glioblastoma (the most aggressive form of adult brain cancer), specifically what makes the standard chemotherapy + radiation treatment stop working.',
      ip_value:
        'Internal research output — not a client engagement. The finding that the hypothesis did not hold is itself valuable, because it prevents future programs from building on a shaky mechanism.',
    },
    pharma: {
      program_name: 'GBM EscapeMap — L8 War Board internal analysis',
      headline:
        'Three-dataset computational analysis of ZEB1/EMT upregulation as a GBM recurrence escape marker under Stupp (TMZ + RT). Hypothesis NOT supported across three independent datasets — internal franchise-audit output.',
      indication_focus:
        'Recurrent GBM under Stupp regimen — franchise-audit substrate probe.',
      ip_value:
        'Internal-only franchise-audit read. Null-result franchise-audit receipt — prevents building franchise strategy on an unsupported ZEB1/EMT escape mechanism.',
    },
  },
};

/**
 * Return persona-adjusted program-header copy for a pipeline program.
 * Falls back to the English root fields on the passed-in program.
 */
export function getPipelinePersonaHeader(
  program: Pick<PipelineProgram, 'program_id' | 'program_name' | 'headline' | 'indication_focus' | 'ip_value' | 'admissibility'>,
  persona: Persona,
): PipelineProgramCopyFields {
  const overlay = PIPELINE_PROGRAM_PERSONA_COPY[program.program_id]?.[persona];
  return {
    program_name: overlay?.program_name ?? program.program_name,
    headline: overlay?.headline ?? program.headline,
    indication_focus: overlay?.indication_focus ?? program.indication_focus,
    ip_value: overlay?.ip_value ?? program.ip_value,
    admissibility: overlay?.admissibility ?? program.admissibility,
  };
}
