// AUTO-GENERATED by w-research-kb.py — public research hub data
// No trial identifiers, no target/asset names, no partner names.
import type { VerticalPageData } from '@/components/audience/VerticalSurface';
import { BookOpen, Layers, ClipboardCheck, ShieldCheck } from 'lucide-react';

export const RESEARCH_PAGE_DATA: VerticalPageData = {
  eyebrow: 'Research',
  title: 'The mechanism-alignment layer, in the open',
  subtitle: 'Chapters, modules, receipts. What we know, and how we know it.',
  sections: [
    {
      id: 'why',
      label: 'Why research',
      eyebrow: 'Section 1 · Framing',
      headline: 'The mechanism-alignment layer is a research question, not a marketing claim.',
      Icon: BookOpen,
      body: [
    'CrisPRO exists because the same failure keeps happening: pivotal oncology trials run against unstratified populations, wash out on average, and hide their responders inside the negative arm.',
    'The research layer of the site is where we work in the open — chapters, modules, and receipts.',
  ],
      cta: {
        label: 'Read the chapters',
        href: '/kb/',
        helper: 'Fourteen chapters, categorical, no program specifics.',
      },
    },
    {
      id: 'chapters',
      label: 'Chapters',
      eyebrow: 'Section 2 · Chapters',
      headline: 'Fourteen chapters covering the layer end-to-end.',
      Icon: Layers,
      body: [
    'Every chapter is a category: why trials fail, the mechanism-alignment layer, the eight-dimensional vector, the trial-vector library, the fit engine, target-lock, the SL bridge, the biomarker taxonomy, escape-map, two-gate selection, the holistic score, governance, the public ledger, and the roadmap.',
    'No chapter names a specific trial or asset. Program-specific decodes live in the public ledger.',
  ],
      cta: {
        label: 'Open the knowledge base',
        href: '/kb/',
      },
    },
    {
      id: 'modules',
      label: 'Modules',
      eyebrow: 'Section 3 · Executable modules',
      headline: 'Fifteen executable modules mapped to chapters.',
      Icon: ClipboardCheck,
      body: [
    'Each module is a callable analysis unit — a stratification, a trial-design diagnostic, a look-alike search, an audit.',
    'Every module is anchored to a chapter, so the theory and the executable both travel with it.',
  ],
      cta: {
        label: 'Browse modules',
        href: '/kb/',
      },
    },
    {
      id: 'ledger',
      label: 'Ledger',
      eyebrow: 'Section 4 · Public ledger',
      headline: 'Seven programs, forty-two trials, decoded before we open a sales conversation.',
      Icon: ShieldCheck,
      body: [
    'The chapters and modules are how we work. The public ledger is what falls out — the record of decoded programs.',
    'Every case in the ledger cites its own source. Every case can be reproduced from the same fit engine.',
  ],
      cta: {
        label: 'Open the ledger',
        href: '/ledger/',
      },
    },
  ],
};
